name: UB22.04_NO_MED

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mpich
        wget https://github.com/FreeFem/FreeFem-sources/releases/download/v4.14-testActions/FreeFEM-4.14-amd64-22.04.deb
        sudo apt install ./FreeFEM-4.14-amd64-22.04.deb
    - name: configure
      run: autoreconf -i && ./configure
    - name: make
      run: make && sudo make install
#    - name: make check
#      run: make check
